### ISSUE TITLE
Link not working 

### ISSUE THREAD

**Issue by djdirty60** [h53h54h55/Syncler#1]
Good day, the link of SYNCLER V2 / BETA is not working, would you like to take a look at that.

Thank you in advance

**Comment by h53h54h55** [comment]
Link appears ok.  No other users highlighting issues.  Try deleting the installed packages and then deleted the URL.  Clear cache from syncler and from device and reinstall. Beta seems not to like auto updating if the package structure is altered.  For future requests log with Reddit for a faster response.

**Comment by djdirty60** [comment]
Leg dit eens uit dan?

![IMG_0402](https://github.com/h53h54h55/Syncler/assets/13561831/44022956-f25d-4713-bb66-40f5389c4ec0)

**Comment by djdirty60** [comment]
> Explain this then?
> 
> ![IMG_0402](https://private-user-images.githubusercontent.com/13561831/316296913-44022956-f25d-4713-bb66-40f5389c4ec0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzE1MTIsIm5iZiI6MTcxMTI3MTIxMiwicGF0aCI6Ii8xMzU2MTgzMS8zMTYyOTY5MTMtNDQwMjI5NTYtZjI1ZC00NzEzLWJiNjYtNDBmNTM4OWM0ZWMwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQwOTA2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGQ2ZjFiN2I1NmY5ZDI4NTdiZDRlNTc1YTdjMTNhMTY2MDBjMDIyZjViODM4ZWQ2ODk1ZjY5MDk3Y2YzOTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cZFi2-l22dw6-qEFME5GNYqAsLeJ-8GbzYhS0IB5tbI)

Error found

![IMG_0403](https://github.com/h53h54h55/Syncler/assets/13561831/ab10dedf-b037-480d-ac56-0160afbf4b12)

**Comment by h53h54h55** [comment]
Firstly - I asked you communicate through my reddit page.
Secondly - I don't appreciate the tone.  You PAID for Syncler…. but vendor providers do this for FREE.  I volunteer my time to make this community better.
Three - you provided no information with your ‘complaint’ so how do you expect an answer?  Where are you, what device, how much ram, what vpn etc..  all usefull to know.
Finally - I have installation guides on reddit.  I cant be responsible for other people posting the link name incorrectly or for autocorrect or if you are reading old threads.

**Comment by djdirty60** [comment]
> Firstly - I asked you communicate through my reddit page. Secondly - I don't appreciate the tone. You PAID for Syncler…. but vendor providers do this for FREE. I volunteer my time to make this community better. Three - you provided no information with your ‘complaint’ so how do you expect an answer? Where are you, what device, how much ram, what vpn etc.. all usefull to know. Finally - I have installation guides on reddit. I cant be responsible for other people posting the link name incorrectly or for autocorrect or if you are reading old threads.

It's wrong on your own GitHub, and I'll decide where I post something.

**Comment by h53h54h55** [comment]
…. and you’ll clearly ignore instructions to read reddit
